const puppeteer = require('puppeteer');

exports.generatePdf = async (htmlContent, options = {}) => {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // Add watermark if needed
    if (options.isWatermarked) {
        await page.evaluate(() => {
            const watermark = document.createElement('div');
            watermark.innerText = 'Generated by ShaadiBio';
            watermark.style.position = 'fixed';
            watermark.style.bottom = '10px';
            watermark.style.right = '10px';
            watermark.style.opacity = '0.5';
            watermark.style.fontSize = '12px';
            watermark.style.zIndex = '9999';
            document.body.appendChild(watermark);
        });
    }

    const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '0', right: '0', bottom: '0', left: '0' }
    });

    await browser.close();
    return pdfBuffer;
};
