const puppeteer = require('puppeteer');

exports.generatePdf = async (htmlContent, options = {}) => {
    console.log('--- PDF GENERATION STARTED ---');
    console.log('HTML content length:', htmlContent?.length || 0);
    console.log('Options:', options);

    let browser;
    try {
        browser = await puppeteer.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-accelerated-2d-canvas',
                '--no-first-run',
                '--no-zygote',
                '--disable-gpu'
            ]
        });
        console.log('Browser launched successfully');

        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
        console.log('Page content set');

        // Add watermark if needed
        if (options.isWatermarked) {
            await page.evaluate(() => {
                const watermark = document.createElement('div');
                watermark.innerText = 'Generated by ShaadiBio';
                watermark.style.position = 'fixed';
                watermark.style.bottom = '10px';
                watermark.style.right = '10px';
                watermark.style.opacity = '0.5';
                watermark.style.fontSize = '12px';
                watermark.style.zIndex = '9999';
                document.body.appendChild(watermark);
            });
        }

        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '0', right: '0', bottom: '0', left: '0' }
        });

        console.log('PDF generated, buffer size:', pdfBuffer.length);
        return pdfBuffer;

    } catch (error) {
        console.error('--- PDF GENERATION ERROR ---');
        console.error('Error:', error.message);
        console.error('Stack:', error.stack);
        throw error;
    } finally {
        if (browser) {
            await browser.close();
            console.log('Browser closed');
        }
    }
};
